=== deNBI/fts3-databases/database_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "path": { "type": "string" },
    "doi": { "type": "string" },
    "versions": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "path": { "type": "string" },
          "files": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "object",
              "properties": {
                "source": { "type": "string" },
                "directory": { "type": "boolean" },
                "allow_filter": {
                  "type": "array",
                  "items": { "type": "string" }
                },
                "ignore_filter": {
                  "type": "array",
                  "items": { "type": "string" }
                },
                "zenodo": { "type": "boolean" }
              },
              "required": ["source"]
            }
          }
        },
        "required": ["name"]
      }
    }
  },
  "required": ["name", "path", "versions"]
}

=== deNBI/fts3-databases/databases/plsdb.json
{
  "name": "PLSDB",
  "path": "plsdb",
  "doi": "10.1093/nar/gky1050", 
  "versions": [
    {
      "name": "2021_06_23_v2",
      "files": [
        {
          "source": "https://ccb-microbe.cs.uni-saarland.de/plsdb/plasmids/download/plasmids_meta.tar.bz2"
        },
        {
          "source": "https://ccb-microbe.cs.uni-saarland.de/plsdb/plasmids/download/plsdb.fna.bz2"
        }
      ]
    }
  ]
}
